export const FETCH_RENTALS = 'FETCH_RENTALS';
export const FETCH_HOUSES = 'FETCH_HOUSES';
export const FETCH_RENTAL_BY_ID_SUCCESS = 'FETCH_RENTAL_BY_ID_SUCCESS';
export const FETCH_HOUSE_BY_ID_SUCCESS = 'FETCH_HOUSE_BY_ID_SUCCESS';
export const FETCH_RENTAL_BY_ID_INIT = 'FETCH_RENTAL_BY_ID_INIT';
export const FETCH_HOUSE_BY_ID_INIT = 'FETCH_HOUSE_BY_ID_INIT';
export const FETCH_RENTALS_SUCCESS = 'FETCH_RENTALS_SUCCESS';
export const FETCH_HOUSES_SUCCESS = 'FETCH_HOUSES_SUCCESS';

export const FETCH_USER_BOOKINGS_SUCCESS = 'FETCH_USER_BOOKINGS_SUCCESS';
export const FETCH_USER_HOUSE_BOOKINGS_SUCCESS = 'FETCH_USER_HOUSE_BOOKINGS_SUCCESS';
export const FETCH_USER_BOOKINGS_FAIL = 'FETCH_USER_BOOKINGS_FAIL';
export const FETCH_USER_HOUSE_BOOKINGS_FAIL = 'FETCH_USER_HOUSE_BOOKINGS_FAIL';
export const FETCH_USER_BOOKINGS_INIT = 'FETCH_USER_BOOKINGS_INIT';
export const FETCH_USER_HOUSE_BOOKINGS_INIT = 'FETCH_USER_HOUSE_BOOKINGS_INIT';
export const UPDATE_BOOKINGS='UPDATE_BOOKINGS';
export const UPDATE_HOUSE_BOOKINGS='UPDATE_HOUSE_BOOKINGS';



export const FETCH_RENTALS_INIT = 'FETCH_RENTALS_INIT';
export const FETCH_HOUSES_INIT = 'FETCH_HOUSES_INIT';
export const FETCH_RENTALS_FAIL = 'FETCH_RENTALS_FAIL';
export const FETCH_HOUSES_FAIL = 'FETCH_HOUSES_FAIL';

export const UPDATE_RENTAL_SUCCESS = 'UPDATE_RENTAL_SUCCESS';
export const UPDATE_HOUSE_SUCCESS = 'UPDATE_HOUSE_SUCCESS';
export const UPDATE_RENTAL_FAIL = 'UPDATE_RENTAL_FAIL';
export const UPDATE_HOUSE_FAIL = 'UPDATE_HOUSE_FAIL';
export const RESET_RENTAL_ERRORS = 'RESET_RENTAL_ERRORS';
export const RESET_HOUSE_ERRORS = 'RESET_HOUSE_ERRORS';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const RELOAD_MAP = 'RELOAD_MAP';
export const RELOAD_MAP_FINISH = 'RELOAD_MAP_FINISH';
